#!/bin/bash -e

cd $(dirname $0)/..

# Clean up at the end
trap "docker-compose down --volumes --remove-orphans" 0

# Start clean
docker-compose down --volumes --remove-orphans

# Create volume
docker volume create --name stack-global > /dev/null

# rebuild if necessary
docker-compose build dev

# Run dev script or use what is passed in as arguments
docker-compose run --rm --service-ports dev "${@-./run-dev}"
