#!/bin/bash -e

cd $(dirname $0)/..

auto/dev-environment mkdir -p dist # kind of gross but stack won't create the directory with --copy-bins
auto/build --copy-bins

docker build -t myregistry.com/example:12345 .

# this continer can be run with docker run -t myregistry.com/example:12345

# the following is out of scope but you would probably do something like

# docker push myregistry.com/example:12345

# docker tag myregistry.com/example:12345 myregistry.com:latest

# update my deployment repo with the new runtime container which will
# be picked up by CI and the new version gets deployed
